server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: {{SPRING_DATASOURCE_URL}}
    username: {{SPRING_DATASOURCE_USERNAME}}
    password: {{SPRING_DATASOURCE_PASSWORD}}
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    jackson:
      serialization:
        fail-on-empty-beans: false